function _init()
    cartdata("calebstein1_terradestined_1")
    poke(0x5f2e, 1)
    init_timer()
    init_dialog()
    init_music()
    init_camera()
    init_map()
    init_player()
    init_npc()
    init_enemies()
    load_strings()
end

function _update()
    increment_or_reset_timer()
    set_camera()
    update_player()
    update_poi_sprite()
    set_bg()
    set_active_npc_list()
    play_music_for_location()
end

function _draw()
    cls(bg)
    map(0,0)
    draw_sprites()
    draw_active_npc()
    draw_dialog()
end